name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_npm
        uses: actions/cache@v3
        env:
          cache-name: dependencies-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |  # 用途：当找不到以某个 hash 结尾的文件的时候，可以退而求其次寻找某个名字开头的文件用于后续 jobs
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      js-file: ${{ steps.js_file.outputs.js_file_name }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache_npm
        uses: actions/cache@v3
        env:
          cache-name: dependencies-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |  # 用途：当找不到以某个 hash 结尾的文件的时候，可以退而求其次寻找某个名字开头的文件用于后续 jobs
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Get JS file name in dist folder
        id: js_file
        run: find dist/assets/*.js -type f -execdir echo js_file_name={} >> $GITHUB_OUTPUT \;
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output file list
        run: ls
      - name: Print JS file name
        run: echo "${{ needs.build.outputs.js-file }}"
      - name: Deploy
        run: echo "Deploying..."
